version: '2'

services:
  server:
    build: .
    ports:
      - '3003:3003'
    depends_on:
      - 'mongo'
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
  